### ISSUE TITLE
AMP as a Uzebox sound card?

### ISSUE THREAD

**Issue by danboid** [JarkkoPFC/arduino-music-player#11]
Hi Jarkko

Did you already know about the open source 8 bit games console the Uzebox?

https://uzebox.org/

It is also an AVR device. It only has 4K RAM and part of that gets used by the Uzebox sound engine, which doesn't currently have MOD/XM etc playback support.

Do you think it would be possible to trigger a sample or two over the MOD/XM/SID or whatever is being played by AMP, just using one Teensy or similar? Maybe have the tracker file playing in the left and the sample(s) in the right channel?

Might it be possible to hook something running AMP up to the Uzebox AVR MCU via SPI or UART and have it function as a simple soundcard for playing MOD files and samples for SFX?

Which device would you recommend for this purpose, if you think it could work, after a few tweaks to AMP and the Uzebox kernel?

Just wondering!

Thanks

**Comment by JarkkoPFC** [comment]
You can have AMP playing a MOD and programmatically trigger the samples (with given note, volume & effect) included in the MOD on the channels. For example, if you have a 4 channel MOD, you could allocate an extra channel in a tracker for the MOD and then trigger samples in that extra channel to avoid messing with the music.

**Comment by danboid** [comment]
Absolutely you could yes! How did that totally obvious use not occur to me? Ha!

Any similar things to this been done before that you're aware of, using AMP?

**Comment by JarkkoPFC** [comment]
Not that I'm aware of. You can check the [Making Electronic Instruments](https://github.com/JarkkoPFC/arduino-music-player#making-electronic-instruments) section in the readme for some details.
Edit: Forgot that you don't actually need to add an extra track in a tracker for the effect channel but can just do it in the code. The [pmf_player.ino](https://github.com/JarkkoPFC/arduino-music-player/blob/master/pmf_player/pmf_player.ino) has example code for it.
