### ISSUE TITLE
Error when compiling to SAM21 Arduino Zero

### ISSUE THREAD

**Issue by ypatidisioannis** [JarkkoPFC/arduino-music-player#3]
Hi! I am trying to use this library with Arduino Zero but with no luck , I get the following errors : 

sketch\pmf_player.cpp.o: In function `pmf_player::stop()':

sketch/pmf_player.cpp:275: undefined reference to `pmf_player::stop_playback()'

sketch\pmf_player.cpp.o: In function `pmf_player::start(void const*)':

sketch/pmf_player.cpp:269: undefined reference to `pmf_player::start_playback()'

sketch\pmf_player.cpp.o: In function `pmf_player::update()':

sketch/pmf_player.cpp:282: undefined reference to `pmf_player::get_mixer_buffer()'

sketch/pmf_player.cpp:292: undefined reference to `pmf_player::mix_buffer(pmf_player::mixer_buffer&, unsigned int)'

sketch/pmf_player.cpp:310: undefined reference to `pmf_player::visualize_pattern_frame()'

collect2.exe: error: ld returned 1 exit status

exit status 1
Error compiling for board Arduino/Genuino Zero (Native USB Port).

Can you please help out?

**Comment by JarkkoPFC** [comment]
Added instructions to the README.md
