### ISSUE TITLE
Converter: Some headers not included

### ISSUE THREAD

**Issue by fgenesis** [JarkkoPFC/arduino-music-player#4]
Hey, i'm trying to compile the converter but some files are nowhere to be found:

    #include "sxp_src/core/core.h"
    #include "sxp_src/core/main.h"
    #include "sxp_src/core/fsys/fsys.h"
    #include "sxp_src/core/containers.h"
    #include "sxp_src/core/sort.h"

I've found [this old post](https://www.gamedev.net/forums/topic/626400-new-spin-x-source-release/) from you but the links are dead. I've tried everything reachable from there, http://spinxengine.com/ and http://www.profoundic.com/ as well but nope.

If possible please provide those headers, or at least a download location so that i don't have to reverse construct the code. I plan to make some modifications to the converter, mainly to export samples as separate arrays to get around the dumb 64k array size limit of avr-gcc.

Background: I'm in the process of writing a demo using your player for the music, on an Atmega2560, using PWM output for the lack of a proper DAC. 

The recent update was great but introduced some problems that i've fixed locally -- I've done some light modifications to shed some CPU cycles and improve quality, if you're interested in those changes i'll prepare a PR after cleaning up the mess a bit.

**Comment by JarkkoPFC** [comment]
Hi, I'll look into adding the missing files in the following weekend. It would be also interesting to have a look to the improvements you have made.
