### ISSUE TITLE
Wishlist: Linux gcc compilation support for pmf_converter?

### ISSUE THREAD

**Issue by sta-c0000** [JarkkoPFC/arduino-music-player#6]
Wishlist: Linux gcc compilation support for pmf_converter

I see there is mention of Linux platform support in the `sxp_src` tree files.  Tried compiling with `gcc` using the `PFC_RELEASE PFC_COMPILER_GCC PFC_PLATFORM_LINUX64` options without luck.  Appears might be more work required than a few missing includes (e.g. `<sched.h>` & `<unistd.h>`) and what not.

What are your thoughts?

BTW, `pmf_player` is very cool, thank you.  It worked _out of the box_ (as is) on an **Adafruit Circuit Playground Express**.  [Here's a quick video](https://gofile.io/?c=dRFmYA) connected to battery and using tiny on-board speaker.  The "_neopixels_" are using a simple `.setPixelColor` library call in `example_visualization`.

Thanks!

**Comment by JarkkoPFC** [comment]
Glad to hear the player works for you!

Thanks for pointing out the Linux issues with the converter. I'll have a look.

**Comment by JarkkoPFC** [comment]
Should work now (tested on "gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0")
FYI, added a makefile, so you can just run "make build=retail" in pmf_converter/build/gcc dir to compile 64bit retail version, or if you run on 32bit "make platform=linux32 build=retail".

**Comment by sta-c0000** [comment]
Brilliant, worked perfectly!
Thank you.
