### ISSUE TITLE
Get channel_info ahead of time?

### ISSUE THREAD

**Issue by felipemanga** [JarkkoPFC/arduino-music-player#7]
Hey,
I've ported your player to the Pokitto and ran into a little problem: 
I'd like to get information about what note is going to play, maybe a second ahead of time.
Is there any way to do that, other than buffering all the sample data?

**Comment by JarkkoPFC** [comment]
I can't think of any direct way to do this. The most memory efficient way would probably be to modify the code to decode and buffer track data few rows ahead.
