### ISSUE TITLE
Teensy Mod player from SD Card

### ISSUE THREAD

**Issue by CleversonSA** [JarkkoPFC/arduino-music-player#8]
Hello,

I've build your arduino mod player a few years ago as shown at your Youtube Video from 2014. It worked well for some 4 ch mod files I had at my collection. 
Yesterday your vids came on my yt timeline again, and revisited it. I've seen you made a port for Teensy as well.
So Is it possible to read .mod files direct from a SD Card? I realized build a diy mod portable player.

Regards.

**Comment by JarkkoPFC** [comment]
The mod player requires fast random access to the file (unlike mp3 for example) which would be very inefficient to access straight from SD card, so you would need to load the file from SD card to flash memory or RAM first.
